[package]
name = "nametakenbonk/enaltcast"
description = "A fast and easy to use caster"
lisence = "MIT"
authors = ["Alternative", "EnumEnv"]
version = "0.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**.lock", "Packages", "**.json"]

[dependencies]
fastsignal = "lucasmzreal/fastsignal@10.4.0"